{
 "title": "Home Energy",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Electricity Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Electricity per day past week",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "day = from(bucket: \"HomeEnergy\")\r\n  |> range(start: -7d, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"P1\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ELECTRICITY_USED_TARIFF_2\")\r\n  |> aggregateWindow(every: 1h, fn: spread, createEmpty: false)\r\n  |> aggregateWindow(every: 24h, fn: sum, createEmpty: false)\r\n  |> set(key: \"_field\", value:\"Day\")\r\n\r\nnight = from(bucket: \"HomeEnergy\")\r\n  |> range(start: -7d, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"P1\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ELECTRICITY_USED_TARIFF_1\")\r\n  |> aggregateWindow(every: 1h, fn: spread, createEmpty: false)\r\n  |> aggregateWindow(every: 24h, fn: sum, createEmpty: false)\r\n  |> set(key: \"_field\", value:\"Night\")\r\n  \r\n  //|> rename(columns: {\"ELECTRICITY_USED_TARIFF_1\": \"Nacht\", \"ELECTRICITY_USED_TARIFF_2\": \"Dag\"})\r\nunion(tables: [day, night])\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Electricity per Day",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeEnergy\")\r\n  |> range(start: v.timeRangeStart, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"P1\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"kW\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"CURRENT_ELECTRICITY_USAGE\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> aggregateWindow(every: 24h, fn: sum, createEmpty: false)\r\n  |> set(key: \"_field\", value:\"Day + Night\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Outdoor Temperature",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeNibe\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NIBE F730\")\r\n  |> filter(fn: (r) => r[\"category\"] == \"status\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"outdoor temp.\")\r\n  |> aggregateWindow(every: 24h, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Electricity Day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "day = from(bucket: \"HomeEnergy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"P1\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ELECTRICITY_USED_TARIFF_2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value:\"Day\")\r\n\r\nday"
    }
   ]
  },
  {
   "title": "Electricity Night",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "night = from(bucket: \"HomeEnergy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"P1\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"kWh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ELECTRICITY_USED_TARIFF_1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value:\"Night\")\r\n\r\nnight"
    }
   ]
  },
  { "title": "Electricity Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Power Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeEnergy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"P1\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"kW\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"CURRENT_ELECTRICITY_USAGE\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Power L1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeEnergy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"P1\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"kW\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"INSTANTANEOUS_ACTIVE_POWER_L1_POSITIVE\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Power L2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeEnergy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"P1\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"kW\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"INSTANTANEOUS_ACTIVE_POWER_L2_POSITIVE\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Power L3",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeEnergy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"P1\")\r\n  |> filter(fn: (r) => r[\"unit\"] == \"kW\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"INSTANTANEOUS_ACTIVE_POWER_L3_POSITIVE\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Nibe F730 Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Outdoor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeNibe\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NIBE F730\")\r\n  |> filter(fn: (r) => r[\"category\"] == \"status\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"outdoor temp.\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Indoor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeNibe\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NIBE F730\")\r\n  |> filter(fn: (r) => r[\"category\"] == \"climate system 1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"room temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Hot Water Top",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeNibe\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NIBE F730\")\r\n  |> filter(fn: (r) => r[\"category\"] == \"status\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hot water top\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Hot Water Charging",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeNibe\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NIBE F730\")\r\n  |> filter(fn: (r) => r[\"category\"] == \"status\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"hot water charging\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Condensor Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeNibe\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NIBE F730\")\r\n  |> filter(fn: (r) => r[\"category\"] == \"compressor module \")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"condenser out\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Condensor Return",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeNibe\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NIBE F730\")\r\n  |> filter(fn: (r) => r[\"category\"] == \"compressor module \")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"condenser return\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Nibe F730 Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Degree Minutes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeNibe\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NIBE F730\")\r\n  |> filter(fn: (r) => r[\"category\"] == \"status\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"degree minutes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Defrosting",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeNibe\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NIBE F730\")\r\n  |> filter(fn: (r) => r[\"category\"] == \"defrosting\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value, air velocity sensor\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Compressor Operating",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeNibe\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NIBE F730\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"compressor operating time\")\r\n  |> derivative(unit: 1h, nonNegative: true)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Compressor Operating Hot Water",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeNibe\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NIBE F730\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"compressor operating time hot water\")\r\n  |> derivative(unit: 1h, nonNegative: true)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Compressor Operating Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeNibe\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NIBE F730\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"compressor operating time\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Compressor Operating Time Hot Water",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeNibe\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"NIBE F730\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"compressor operating time hot water\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield()"
    }
   ]
  }
 ]
}