{
 "title": "Home Server",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_user\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\r\n  |> group(columns: [\"cpu\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Docker CPU",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"container_image\"])\r\n  |> last()\r\n  |> group(columns: [\"com.docker.compose.project\"])\r\n  |> sum()\r\n  |> keep(columns: [\"com.docker.compose.project\", \"_value\"])\r\n  |> rename(columns: {\"_value\": \"\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Docker Memory",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"container_image\"])\r\n  |> last()\r\n  |> group(columns: [\"_measurement\", \"_field\", \"com.docker.compose.project\"])\r\n  |> sum()\r\n  |> keep(columns: [\"com.docker.compose.project\", \"container_image\", \"_value\"])\r\n  |> rename(columns: {\"_value\": \"\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "SSD",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"sdb2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> group(columns: [\"device\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "HDD",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"sda1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> group(columns: [\"device\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Time Capsule",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"//192.168.1.2/jacco\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> group(columns: [\"device\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Data Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"HOME-Server\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"enp1s0\")\r\n  |> group(columns: [\"interface\"])\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"sent\")"
    }
   ]
  },
  {
   "title": "Data Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"HOME-Server\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"enp1s0\")\r\n  |> group(columns: [\"interface\"])\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"recv\")"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp\")\r\n  |> filter(fn: (r) => r[\"sensor\"] == \"coretemp_core_0\" or r[\"sensor\"] == \"coretemp_core_1\" or r[\"sensor\"] == \"coretemp_core_2\" or r[\"sensor\"] == \"coretemp_core_3\")\r\n  |> group(columns: [\"_measurement\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "WireGuard VPN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_net\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"wireguard\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rx_bytes\" or r[\"_field\"] == \"tx_bytes\")\r\n  //|> filter(fn: (r) => r[\"network\"] == \"eth0\")\r\n  //|> group(columns: [\"eth0\"])\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n  |> yield(name: \"recv\")"
    }
   ]
  },
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Dashy CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"dashy\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"com.docker.compose.project\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.project\", \"_value\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Dashy Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"dashy\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.service\", \"_value\"])\r\n  |> rename(columns: {\"com.docker.compose.service\": \"Container\"})\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Downloaders CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"downloaders\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"com.docker.compose.project\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.project\", \"_value\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Downloaders Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"downloaders\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.service\", \"_value\"])\r\n  |> rename(columns: {\"com.docker.compose.service\": \"Container\"})\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "File Browser CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"filebrowser\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"com.docker.compose.project\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.project\", \"_value\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "File Browser Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"filebrowser\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.service\", \"_value\"])\r\n  |> rename(columns: {\"com.docker.compose.service\": \"Container\"})\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Gitea CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"gitea\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"com.docker.compose.project\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.project\", \"_value\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Gitea Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"gitea\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.service\", \"_value\"])\r\n  |> rename(columns: {\"com.docker.compose.service\": \"Container\"})\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Grafana CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"grafana\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"com.docker.compose.project\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.project\", \"_value\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Grafana Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"grafana\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.service\", \"_value\"])\r\n  |> rename(columns: {\"com.docker.compose.service\": \"Container\"})\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Immich CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"immich\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"com.docker.compose.project\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.project\", \"_value\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Immich Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"immich\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.service\", \"_value\"])\r\n  |> rename(columns: {\"com.docker.compose.service\": \"Container\"})\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Influxdb CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"influxdb\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"com.docker.compose.project\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.project\", \"_value\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Influxdb Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"influxdb\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.service\", \"_value\"])\r\n  |> rename(columns: {\"com.docker.compose.service\": \"Container\"})\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Jackett CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"jackett\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"com.docker.compose.project\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.project\", \"_value\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Jackett Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"jackett\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.service\", \"_value\"])\r\n  |> rename(columns: {\"com.docker.compose.service\": \"Container\"})\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Jellyfin CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"jellyfin\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"com.docker.compose.project\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.project\", \"_value\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Jellyfin Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"jellyfin\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.service\", \"_value\"])\r\n  |> rename(columns: {\"com.docker.compose.service\": \"Container\"})\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Kimai CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"kimai\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"com.docker.compose.project\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.project\", \"_value\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Kimai Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"kimai\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.service\", \"_value\"])\r\n  |> rename(columns: {\"com.docker.compose.service\": \"Container\"})\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Librespeed CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"librespeed\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"com.docker.compose.project\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.project\", \"_value\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Librespeed Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"librespeed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.service\", \"_value\"])\r\n  |> rename(columns: {\"com.docker.compose.service\": \"Container\"})\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PhotoPrism CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"photoprism\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"com.docker.compose.project\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.project\", \"_value\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PhotoPrism Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"photoprism\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.service\", \"_value\"])\r\n  |> rename(columns: {\"com.docker.compose.service\": \"Container\"})\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Portainer CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"portainer\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"com.docker.compose.project\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.project\", \"_value\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Portainer Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"portainer\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.service\", \"_value\"])\r\n  |> rename(columns: {\"com.docker.compose.service\": \"Container\"})\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Samba CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"samba\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"com.docker.compose.project\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.project\", \"_value\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Samba Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"samba\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.service\", \"_value\"])\r\n  |> rename(columns: {\"com.docker.compose.service\": \"Container\"})\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Transmission CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"transmission\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"com.docker.compose.project\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.project\", \"_value\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Transmission Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"transmission\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.service\", \"_value\"])\r\n  |> rename(columns: {\"com.docker.compose.service\": \"Container\"})\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Wireguard CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"wireguard\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"com.docker.compose.project\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.project\", \"_value\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Wireguard Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"wireguard\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.service\", \"_value\"])\r\n  |> rename(columns: {\"com.docker.compose.service\": \"Container\"})\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Wordpress CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"wordpress\")\r\n  |> group(columns: [\"_measurement\", \"_field\", \"com.docker.compose.project\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.project\", \"_value\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Wordpress Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"HomeServer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"wordpress\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_start\", \"_stop\", \"com.docker.compose.service\", \"_value\"])\r\n  |> rename(columns: {\"com.docker.compose.service\": \"Container\"})\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}